name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Ruby and Jekyll
      - name: Set up Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # You can adjust the Ruby version as needed

      # Install Jekyll and dependencies
      - name: Install Jekyll
        run: gem install jekyll bundler
      - name: Install dependencies
        run: bundle install

      # Build Jekyll site
      - name: Build Jekyll site
        run: bundle exec jekyll build --destination _site

      # Upload artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: jekyll-site
          path: ./_site

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Download artifacts
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: jekyll-site
          path: ./_site

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: _site
